name: Scheduled Merge Remote Action
on:
  schedule:
    - cron: '0 4 * * *'
    # scheduled for 01:00 every day

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev             # set the branch to merge to
          fetch-depth: 0
      - name: Merge Upstream
        uses: danielmundi/merge-upstream@master
        with:
          upstream: armbian/build      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: dev          # set the branch to merge to
          useremail: daniel@finimundi.com
          username: Daniel Finimundi-auto
